name: Deploy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required to add comments to Pull Requests
  deployments: write # This is required to deactivate deployments

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"
  push:
    branches:
      - "main"
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"

jobs:
  deploy-dev:
    name: Dev Deployment
    uses: aws-samples/aws-terraform-reusable-workflow/.github/workflows/terraform-reusable.yml@v1.3.0
    with:
      deploy: true
      tf-version: ${{ vars.TF_VERSION }}
      aws-region: us-east-1
      environment: "dev"
      ref: v1.3.0
      local-execution-mode: true
      enable-github-modules: true
    secrets:
      terraform-execution-iam-plan-role-arn: ${{ secrets.DEV_AWS_PLAN_ROLE_ARN }}
      terraform-execution-iam-apply-role-arn: ${{ secrets.DEV_AWS_APPLY_ROLE_ARN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-test:
    name: Test Deployment
    needs: [deploy-dev]
    if: github.ref == 'refs/heads/main'
    uses: aws-samples/aws-terraform-reusable-workflow/.github/workflows/terraform-reusable.yml@v1.3.0
    with:
      deploy: true
      tf-version: ${{ vars.TF_VERSION }}
      aws-region: us-west-2
      environment: "test"
      ref: v1.3.0
      local-execution-mode: true
      enable-github-modules: true
    secrets:
      terraform-execution-iam-plan-role-arn: ${{ secrets.TEST_AWS_PLAN_ROLE_ARN }}
      terraform-execution-iam-apply-role-arn: ${{ secrets.TEST_AWS_APPLY_ROLE_ARN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    name: Prod Deployment
    needs: [deploy-test]
    if: github.ref == 'refs/heads/main'
    uses: aws-samples/aws-terraform-reusable-workflow/.github/workflows/terraform-reusable.yml@v1.3.0
    with:
      deploy: true
      tf-version: ${{ vars.TF_VERSION }}
      aws-region: us-east-2
      environment: "prod"
      ref: v1.3.0
      local-execution-mode: true
      enable-github-modules: true
    secrets:
      terraform-execution-iam-plan-role-arn: ${{ secrets.PROD_AWS_PLAN_ROLE_ARN }}
      terraform-execution-iam-apply-role-arn: ${{ secrets.PROD_AWS_APPLY_ROLE_ARN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
