name: Deploy

permissions:
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required to add comments to Pull Requests
  deployments: write # This is required to deactivate deployments

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"
  push:
    branches:
      - "main"
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    name: Progressive Deployment
    uses: aws-samples/aws-terraform-reusable-workflow/.github/workflows/terraform-reusable.yml@v1.0.0
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        include:
          - environment: DEV-US-EAST-2
            region: us-east-2
          - environment: TST-US-EAST-2
            region: us-east-2
          - environment: PRD-US-EAST-2
            region: us-east-2
    with:
      deploy: true
      tf-version: ${{ vars.TF_VERSION }}
      tf-organization: ${{ vars.TF_ORGANIZATION }}
      tf-hostname: ${{ vars.TF_HOSTNAME }}
      tf-workspace: ${{ vars.APP_NAME }}-${{ matrix.environment }}
      aws-region: ${{ matrix.region }}
      environment: ${{ matrix.environment }}
    secrets:
      tf-token: ${{ secrets.TF_TOKEN }}
