name: Terraform test PR

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  deployments: write # This is required to deactivate deployments

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

concurrency:
  group: terraform-test
  cancel-in-progress: false

jobs:
  test-deploy:
    name: Test Deployment
    runs-on: ubuntu-latest
    if: ${{ ! github.event.pull_request.draft }}
    defaults:
      run:
        shell: bash
    environment:
      name: PR-${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TF_PLAN_ROLE_ARN }}
          role-session-name: terraform-test-role
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform test
        run: terraform test
  deactivate-deployment:
    needs: [test-deploy]
    name: Deactivate deployment
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: pr-${{ github.event.number }}
          onlyDeactivateDeployments: true
